name: Tests
on: [push, pull_request]
jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM Dependences
        run: npm i -D

      - name: Build
        run: npm run build